soapui.home=C:/Raja/SoapUI-5.4.0
soapui.project=C:/Users/c030974/Desktop/Backup/ReportGen/6-29-PersonToPersonPayments-soapui-Zelleproject.xml
results.dir=C:/Users/c030974/Desktop/Backup/ReportGen/tmp/results
